version: "3"

networks:
  default:
    name: demoapp
    external: true

services:
  mysql:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
      - ./data/log:/var/log/mysql
    environment:
      TZ: "Asia/Bangkok"
      MYSQL_ROOT_PASSWORD: "rangsan2001"
      MYSQL_DATABASE: "rangsan"
      MYSQL_USER: "rangsan2234"
      MYSQL_PASSWORD: "goodguy2234"
    ports:
      - "3306:3306"
