version: '3.4'

networks:
  backend:
    name: demoapp
    external: true
  default:
    driver: bridge

services:
  authenticationapi:
    image: ${DOCKER_REGISTRY-}authenticationapi
    build:
      context: .
      dockerfile: AuthenticationAPI/Dockerfile
    networks:
        - default
        - backend
  demowebmvc:
    image: ${DOCKER_REGISTRY-}demowebmvc
    build:
      context: .
      dockerfile: DemoWebMVC/Dockerfile
    networks:
        - default
